# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anna < Formula
  desc "Anna Static Site Generator"
  homepage "https://github.com/anna-ssg/anna"
  version "4.0.0-rc-3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/anna-ssg/anna/releases/download/v4.0.0-rc-3/anna_Darwin_x86_64.tar.gz"
      sha256 "5911decb3d37da59886c1c6579165baf993b0d517aa3ed8a2aae72714edcc0b5"

      def install
        bin.install "anna"
      end
    end
    on_arm do
      url "https://github.com/anna-ssg/anna/releases/download/v4.0.0-rc-3/anna_Darwin_arm64.tar.gz"
      sha256 "cfff360da6ad1a29a903f802c7ca23e4df1d754fb439084937e8ec97d53c853d"

      def install
        bin.install "anna"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anna-ssg/anna/releases/download/v4.0.0-rc-3/anna_Linux_x86_64.tar.gz"
        sha256 "bfc1e41baedd0b80803fee90b177abb740643b438a6b1ad435deb41706a7568e"

        def install
          bin.install "anna"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anna-ssg/anna/releases/download/v4.0.0-rc-3/anna_Linux_arm64.tar.gz"
        sha256 "799c1f86d87d9e9b544c1091cbc5a74d679367f15e74fefff8f23512e4591218"

        def install
          bin.install "anna"
        end
      end
    end
  end

  test do
    system "#{bin}/anna version"
  end
end
