# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anna < Formula
  desc "Anna Static Site Generator"
  homepage "https://github.com/anna-ssg/anna"
  version "4.0.0-rc-1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/anna-ssg/anna/releases/download/4.0.0-rc-1/anna_Darwin_x86_64.tar.gz"
      sha256 "488ce62fd96a151fe1f323dc1e88179f9a53cb70c976b037c9044a36c5aaf9b8"

      def install
        bin.install "anna"
      end
    end
    on_arm do
      url "https://github.com/anna-ssg/anna/releases/download/4.0.0-rc-1/anna_Darwin_arm64.tar.gz"
      sha256 "adcf779fc07feda471de00ef1e03ebb1dfcb53b1e8c818b854999068783c9b89"

      def install
        bin.install "anna"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anna-ssg/anna/releases/download/4.0.0-rc-1/anna_Linux_x86_64.tar.gz"
        sha256 "e8935b92640fd1fec62705853bba6ac05aff679eeb08b03555b80c794846382b"

        def install
          bin.install "anna"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anna-ssg/anna/releases/download/4.0.0-rc-1/anna_Linux_arm64.tar.gz"
        sha256 "ca1b3e055110909ad1ddb5ffb0972d4e6d1afe51e884874c44765253ccba464d"

        def install
          bin.install "anna"
        end
      end
    end
  end

  test do
    system "#{bin}/anna version"
  end
end
