# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anna < Formula
  desc "Anna Static Site Generator"
  homepage "https://github.com/anna-ssg/anna"
  version "4.0.0-rc-4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/anna-ssg/anna/releases/download/v4.0.0-rc-4/anna_Darwin_x86_64.tar.gz"
      sha256 "19d0b2e09515dfe2bef0596a3fc885d1d68edbfd9c6a70e602f566515e6407a0"

      def install
        bin.install "anna"
      end
    end
    on_arm do
      url "https://github.com/anna-ssg/anna/releases/download/v4.0.0-rc-4/anna_Darwin_arm64.tar.gz"
      sha256 "5dc2c3f7279f70017070c5eac41271e342d8ddeebfb753fab7cced951d5b26fb"

      def install
        bin.install "anna"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anna-ssg/anna/releases/download/v4.0.0-rc-4/anna_Linux_x86_64.tar.gz"
        sha256 "b53aaa0ec0e1a3b85ee1c7236b18137ba15623cc0057b7a6eb4c3f2780310f3e"

        def install
          bin.install "anna"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anna-ssg/anna/releases/download/v4.0.0-rc-4/anna_Linux_arm64.tar.gz"
        sha256 "2f8d63dcb8e038cee9512ed396b7c660b9724604d4a6b5f2a04f60cabc6030fd"

        def install
          bin.install "anna"
        end
      end
    end
  end

  test do
    system "#{bin}/anna version"
  end
end
